#define MV_NO_MOVE 0x00
#define MV_POUND 0x01
#define MV_KARATE_CHOP 0x02
#define MV_DOUBLESLAP 0x03
#define MV_COMET_PUNCH 0x04
#define MV_MEGA_PUNCH 0x05
#define MV_PAY_DAY 0x06
#define MV_FIRE_PUNCH 0x07
#define MV_ICE_PUNCH 0x08
#define MV_THUNDERPUNCH 0x09
#define MV_SCRATCH 0x0a
#define MV_VICEGRIP 0x0b
#define MV_GUILLOTINE 0x0c
#define MV_RAZOR_WIND 0x0d
#define MV_SWORDS_DANCE 0x0e
#define MV_CUT 0x0f
#define MV_GUST 0x10
#define MV_WING_ATTACK 0x11
#define MV_WHIRLWIND 0x12
#define MV_FLY 0x13
#define MV_BIND 0x14
#define MV_SLAM 0x15
#define MV_VINE_WHIP 0x16
#define MV_STOMP 0x17
#define MV_DOUBLE_KICK 0x18
#define MV_MEGA_KICK 0x19
#define MV_JUMP_KICK 0x1a
#define MV_ROLLING_KICK 0x1b
#define MV_SAND_ATTACK 0x1c
#define MV_HEADBUTT 0x1d
#define MV_HORN_ATTACK 0x1e
#define MV_FURY_ATTACK 0x1f
#define MV_HORN_DRILL 0x20
#define MV_TACKLE 0x21
#define MV_BODY_SLAM 0x22
#define MV_WRAP 0x23
#define MV_TAKE_DOWN 0x24
#define MV_THRASH 0x25
#define MV_DOUBLE_EDGE 0x26
#define MV_TAIL_WHIP 0x27
#define MV_POISON_STING 0x28
#define MV_TWINEEDLE 0x29
#define MV_PIN_MISSILE 0x2a
#define MV_LEER 0x2b
#define MV_BITE 0x2c
#define MV_GROWL 0x2d
#define MV_ROAR 0x2e
#define MV_SING 0x2f
#define MV_SUPERSONIC 0x30
#define MV_SONICBOOM 0x31
#define MV_DISABLE 0x32
#define MV_ACID 0x33
#define MV_EMBER 0x34
#define MV_FLAMETHROWER 0x35
#define MV_MIST 0x36
#define MV_WATER_GUN 0x37
#define MV_HYDRO_PUMP 0x38
#define MV_SURF 0x39
#define MV_ICE_BEAM 0x3a
#define MV_BLIZZARD 0x3b
#define MV_PSYBEAM 0x3c
#define MV_BUBBLEBEAM 0x3d
#define MV_AURORA_BEAM 0x3e
#define MV_HYPER_BEAM 0x3f
#define MV_PECK 0x40
#define MV_DRILL_PECK 0x41
#define MV_SUBMISSION 0x42
#define MV_LOW_KICK 0x43
#define MV_COUNTER 0x44
#define MV_SEISMIC_TOSS 0x45
#define MV_STRENGTH 0x46
#define MV_ABSORB 0x47
#define MV_MEGA_DRAIN 0x48
#define MV_LEECH_SEED 0x49
#define MV_GROWTH 0x4a
#define MV_RAZOR_LEAF 0x4b
#define MV_SOLARBEAM 0x4c
#define MV_POISONPOWDER 0x4d
#define MV_STUN_SPORE 0x4e
#define MV_SLEEP_POWDER 0x4f
#define MV_PETAL_DANCE 0x50
#define MV_STRING_SHOT 0x51
#define MV_DRAGON_RAGE 0x52
#define MV_FIRE_SPIN 0x53
#define MV_THUNDERSHOCK 0x54
#define MV_THUNDERBOLT 0x55
#define MV_THUNDER_WAVE 0x56
#define MV_THUNDER 0x57
#define MV_ROCK_THROW 0x58
#define MV_EARTHQUAKE 0x59
#define MV_FISSURE 0x5a
#define MV_DIG 0x5b
#define MV_TOXIC 0x5c
#define MV_CONFUSION 0x5d
#define MV_PSYCHIC_M 0x5e
#define MV_HYPNOSIS 0x5f
#define MV_MEDITATE 0x60
#define MV_AGILITY 0x61
#define MV_QUICK_ATTACK 0x62
#define MV_RAGE 0x63
#define MV_TELEPORT 0x64
#define MV_NIGHT_SHADE 0x65
#define MV_MIMIC 0x66
#define MV_SCREECH 0x67
#define MV_DOUBLE_TEAM 0x68
#define MV_RECOVER 0x69
#define MV_HARDEN 0x6a
#define MV_MINIMIZE 0x6b
#define MV_SMOKESCREEN 0x6c
#define MV_CONFUSE_RAY 0x6d
#define MV_WITHDRAW 0x6e
#define MV_DEFENSE_CURL 0x6f
#define MV_BARRIER 0x70
#define MV_LIGHT_SCREEN 0x71
#define MV_HAZE 0x72
#define MV_REFLECT 0x73
#define MV_FOCUS_ENERGY 0x74
#define MV_BIDE 0x75
#define MV_METRONOME 0x76
#define MV_MIRROR_MOVE 0x77
#define MV_SELFDESTRUCT 0x78
#define MV_EGG_BOMB 0x79
#define MV_LICK 0x7a
#define MV_SMOG 0x7b
#define MV_SLUDGE 0x7c
#define MV_BONE_CLUB 0x7d
#define MV_FIRE_BLAST 0x7e
#define MV_WATERFALL 0x7f
#define MV_CLAMP 0x80
#define MV_SWIFT 0x81
#define MV_SKULL_BASH 0x82
#define MV_SPIKE_CANNON 0x83
#define MV_CONSTRICT 0x84
#define MV_AMNESIA 0x85
#define MV_KINESIS 0x86
#define MV_SOFTBOILED 0x87
#define MV_HI_JUMP_KICK 0x88
#define MV_GLARE 0x89
#define MV_DREAM_EATER 0x8a
#define MV_POISON_GAS 0x8b
#define MV_BARRAGE 0x8c
#define MV_LEECH_LIFE 0x8d
#define MV_LOVELY_KISS 0x8e
#define MV_SKY_ATTACK 0x8f
#define MV_TRANSFORM 0x90
#define MV_BUBBLE 0x91
#define MV_DIZZY_PUNCH 0x92
#define MV_SPORE 0x93
#define MV_FLASH 0x94
#define MV_PSYWAVE 0x95
#define MV_SPLASH 0x96
#define MV_ACID_ARMOR 0x97
#define MV_CRABHAMMER 0x98
#define MV_EXPLOSION 0x99
#define MV_FURY_SWIPES 0x9a
#define MV_BONEMERANG 0x9b
#define MV_REST 0x9c
#define MV_ROCK_SLIDE 0x9d
#define MV_HYPER_FANG 0x9e
#define MV_SHARPEN 0x9f
#define MV_CONVERSION 0xa0
#define MV_TRI_ATTACK 0xa1
#define MV_SUPER_FANG 0xa2
#define MV_SLASH 0xa3
#define MV_SUBSTITUTE 0xa4
#define MV_STRUGGLE 0xa5
#define MV_SKETCH 0xa6
#define MV_TRIPLE_KICK 0xa7
#define MV_THIEF 0xa8
#define MV_SPIDER_WEB 0xa9
#define MV_MIND_READER 0xaa
#define MV_NIGHTMARE 0xab
#define MV_FLAME_WHEEL 0xac
#define MV_SNORE 0xad
#define MV_CURSE 0xae
#define MV_FLAIL 0xaf
#define MV_CONVERSION2 0xb0
#define MV_AEROBLAST 0xb1
#define MV_COTTON_SPORE 0xb2
#define MV_REVERSAL 0xb3
#define MV_SPITE 0xb4
#define MV_POWDER_SNOW 0xb5
#define MV_PROTECT 0xb6
#define MV_MACH_PUNCH 0xb7
#define MV_SCARY_FACE 0xb8
#define MV_FAINT_ATTACK 0xb9
#define MV_SWEET_KISS 0xba
#define MV_BELLY_DRUM 0xbb
#define MV_SLUDGE_BOMB 0xbc
#define MV_MUD_SLAP 0xbd
#define MV_OCTAZOOKA 0xbe
#define MV_SPIKES 0xbf
#define MV_ZAP_CANNON 0xc0
#define MV_FORESIGHT 0xc1
#define MV_DESTINY_BOND 0xc2
#define MV_PERISH_SONG 0xc3
#define MV_ICY_WIND 0xc4
#define MV_DETECT 0xc5
#define MV_BONE_RUSH 0xc6
#define MV_LOCK_ON 0xc7
#define MV_OUTRAGE 0xc8
#define MV_SANDSTORM 0xc9
#define MV_GIGA_DRAIN 0xca
#define MV_ENDURE 0xcb
#define MV_CHARM 0xcc
#define MV_ROLLOUT 0xcd
#define MV_FALSE_SWIPE 0xce
#define MV_SWAGGER 0xcf
#define MV_MILK_DRINK 0xd0
#define MV_SPARK 0xd1
#define MV_FURY_CUTTER 0xd2
#define MV_STEEL_WING 0xd3
#define MV_MEAN_LOOK 0xd4
#define MV_ATTRACT 0xd5
#define MV_SLEEP_TALK 0xd6
#define MV_HEAL_BELL 0xd7
#define MV_RETURN 0xd8
#define MV_PRESENT 0xd9
#define MV_FRUSTRATION 0xda
#define MV_SAFEGUARD 0xdb
#define MV_PAIN_SPLIT 0xdc
#define MV_SACRED_FIRE 0xdd
#define MV_MAGNITUDE 0xde
#define MV_DYNAMICPUNCH 0xdf
#define MV_MEGAHORN 0xe0
#define MV_DRAGONBREATH 0xe1
#define MV_BATON_PASS 0xe2
#define MV_ENCORE 0xe3
#define MV_PURSUIT 0xe4
#define MV_RAPID_SPIN 0xe5
#define MV_SWEET_SCENT 0xe6
#define MV_IRON_TAIL 0xe7
#define MV_METAL_CLAW 0xe8
#define MV_VITAL_THROW 0xe9
#define MV_MORNING_SUN 0xea
#define MV_SYNTHESIS 0xeb
#define MV_MOONLIGHT 0xec
#define MV_HIDDEN_POWER 0xed
#define MV_CROSS_CHOP 0xee
#define MV_TWISTER 0xef
#define MV_RAIN_DANCE 0xf0
#define MV_SUNNY_DAY 0xf1
#define MV_CRUNCH 0xf2
#define MV_MIRROR_COAT 0xf3
#define MV_PSYCH_UP 0xf4
#define MV_EXTREMESPEED 0xf5
#define MV_ANCIENTPOWER 0xf6
#define MV_SHADOW_BALL 0xf7
#define MV_FUTURE_SIGHT 0xf8
#define MV_ROCK_SMASH 0xf9
#define MV_WHIRLPOOL 0xfa
#define MV_BEAT_UP 0xfb